// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ArViewMap
{
	public partial class DetailViewController : UIViewController
	{
		public DetailViewController (IntPtr handle) : base (handle)
		{
            
		}
	}
}
